ALTER TABLE "Cliente" ADD COLUMN "notas" TEXT;
ALTER TABLE "Cliente" ADD COLUMN "etiqueta" TEXT;
ALTER TABLE "Cliente" ADD COLUMN "latitud" DOUBLE PRECISION;
ALTER TABLE "Cliente" ADD COLUMN "longitud" DOUBLE PRECISION;
ALTER TABLE "Cliente" ADD COLUMN "activo" BOOLEAN NOT NULL DEFAULT true;
